# Generated by Django 5.1.5 on 2025-01-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_profile',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
