# Generated by Django 5.1.5 on 2025-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_customersupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_number',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
